class dicts():
    refer = {"patients.person_id": "patients.subject_id", "patients.zipcode": "patients.zip_code",
             "encounters.encounter_id": "encounters.encntr_id", "procedures.code": "procedures_icd.code",
             "labevents.item_id": "lab_events.item_id", "labevents.numvalue": "labevents.valuenum",
             "apgar_event.item": "apgar_events.item_id", "apgar_event.value": "apgar_events.result_val",
             "apgar_event.time": "apgar_events.time_interval", "apgar_event.baby_no": "apgar_events.result_val_num"}

    operator_dict_int = {"equal": " = ", "not_equal": " <> ",
                         "greater": " > ", "greater_or_equal": " >= ",
                         "less": " < ", "less_or_equal": " <= ",
                         "is_null": " is null", "is_not_null": " is not null ",
                         "between": " BETWEEN ", "not_between": " not BETWEEN "}

    operator_dict_str = {"begins_with": " LIKE '{}%' ", "not_begins_with": " not LIKE '{}%' ",
                         "contains": " LIKE '%{}%' ", "not_contains": " not LIKE '%{}%' ",
                         "ends_with": " LIKE '%{}' ", "not_ends_with": " not LIKE '%{}' ",
                         "equal": " LIKE '{}' ", "not_equal": " not LIKE '{}' ",
                         "is_not_empty": " <> '' ", "is_empty": " = ''",
                         "is_null": " is null ", "is_not_null": " is not null ",
                         "in": " IN ", "not_in": " not IN "}

    dict_no_encntr = {"patients": "encounters", "dt_apgar_items": "apgar_events", "dt_apgarscore":"apgarscore",
                      "dt_lab_items":"lab_events","dt_labitems":"lab_events","dt_lab_items_category":"lab_events",
                      "display_key_event":"para_event","dt_birth_events":"birth_events","dt_icd_procedures":"procedures_icd",
                      "dt_para_events":"para_event","dt_diagnosis":"diagnosis"}

    attr_no_enc = {"patients": ["patients.subject_id", "encounters.person_id"],
                   "dt_apgar_items": ["dt_apgar_items.item_id", "apgar_events.item_id"],
                   "dt_apgarscore":["dt_apgarscore.item_id","apgarscore.item_id"],
                   "dt_lab_items":["dt_lab_items.item_id","lab_events.item_id"],
                   "dt_labitems": ["dt_labitems.item_id", "lab_events.item_id"],
                   "dt_lab_items_category":["dt_lab_items_category.category_id","lab_events.category_id"],
                   "display_key_event":["display_key_event.item_id","para_event.item_id"],
                   "dt_birth_events":["dt_birth_events.item_id","birth_events.display_key"],
                   "dt_icd_procedures":["dt_icd_procedures.code","procedures_icd.code"],
                   "dt_para_events":["dt_para_events.item_id","para_event.item_id"],
                   "dt_diagnosis":["dt_diagnosis.source_identifier","diagnosis.source_identifier"]}

    attributes = ['dt_apgar_items.label', 'dt_apgarscore.event_description', 'dt_birth_events.display_key',
                  'dt_lab_items.label',
                  'dt_lab_items_category.label', 'dt_para_events.display_key', 'dt_vitals.vitals_event',
                  'dt_labitems.labitem_description',
                  'dt_labitems.labitem_description_category', 'dt_icd_procedures.description',
                  'dt_diagnosis.source_string', 'dt_diagnosis.n_source_vocabulary_disp']

    attr_list = ["apgar_events.result_val_str", "birth_events.event_tag", "delivery_outcomes.procedure_type",
                 "fhr_vitals.c_event_disp", "para_event.e_loc_facility_disp", "para_event.e_med_service_disp",
                 "para_event.c_event_disp", "procedures_icd.proc_desc", "diagnosis.source_string"]

    fields = ['patients.subject_id',
              'patients.dob',
              'patients.zipcode',
              'patients.race',
              'patients.ethnicity',
              'patients.state',
              'patients.religion',
              'patients.veteran_status',
              'patients.gender',
              'patients.zip_code',
              'patients.marital_status',
              'encounters.encntr_id',
              'encounters.person_id',
              'encounters.admittime',
              'encounters.birth_dt',
              'encounters.dischtime',
              'encounters.reg_dt_tm',
              'encounters.insurance',
              'encounters.language',
              'encounters.admission_location',
              'encounters.discharge_location',
              'encounters.religion',
              'encounters.marital_status',
              'encounters.ethnicity',
              'encounters.admit_reason',
              'encounters.discharge_disposition',
              'encounters.admission_type',
              'labevents.valuenum_decimal',
              'labevents.charttime',
              'labevents.item_id',
              'labevents.value',
              'labevents.numvalue',
              'labevents.normal_low',
              'labevents.normal_high',
              'labevents.flag',
              'labevents.contributor_system',
              'diagnosis.diagnosis_id',
              'diagnosis.active_ind',
              'diagnosis.probability',
              'diagnosis.source_string_keycap_a_nls',
              'diagnosis.n_string_source_disp',
              'diagnosis.n_source_vocabulary_disp',
              'diagnosis.d_classification_disp',
              'diagnosis.d_diag_type_disp',
              'diagnosis.diag_dt_tm',
              'diagnosis.d_ranking_disp',
              'diagnosis.d_present_on_admit_disp',
              'diagnosis.d_severity_disp',
              'diagnosis.d_severity_class_disp',
              'diagnosis.beg_effective_dt_tm',
              'diagnosis.end_effective_dt_tm',
              'diagnosis.n_concept_source_disp',
              'diagnosis.n_contributor_system_disp',
              'diagnosis.n_active_status_disp',
              'diagnosis.source_identifier',
              'diagnosis.source_string',
              'apgar_events.item_id',
              'apgar_events.result_val_num',
              'apgar_events.time_interval',
              'apgar_events.valid_from_dt_tm',
              'apgar_events.label_name',
              'apgar_events.result_val',
              'apgar_events.result_val_str',
              'birthdatetime.birth_date_time',
              'birthdatetime.label_name',
              'fhr_vitals.c_event_disp',
              'fhr_vitals.normal_low',
              'fhr_vitals.normal_high',
              'procedures_icd.seq_num',
              'procedures_icd.begin_dt_tm',
              'procedures_icd.end_dt_tm',
              'procedures_icd.code',
              'procedures_icd.proc_desc',
              'procedures_icd.source_vocabulary',
              'procedures_icd.contributor_source',
              'procedures_icd.type',
              'apgarscore.item_id',
              'apgarscore.clinical_event_id',
              'apgarscore.display_key',
              'apgarscore.order_id',
              'apgarscore.parent_event_id',
              'apgarscore.result_val',
              'birth_events.display_key',
              'birth_events.baby_name',
              'birth_events.normalcy_display',
              'birth_events.event_tag',
              'birth_events.units',
              'delivery_outcomes.surgical_case_id',
              'delivery_outcomes.primary_proc_ind',
              'delivery_outcomes.surgery_start_date',
              'delivery_outcomes.surgery_stop_date',
              'delivery_outcomes.procedure_start_date',
              'delivery_outcomes.schedule_type',
              'delivery_outcomes.procedure_type',
              'delivery_outcomes.procedure_text',
              'dt_apgar_items.item_id',
              'dt_apgar_items.label',
              'dt_apgarscore.item_id',
              'dt_apgarscore.event_cd',
              'dt_apgarscore.event_description',
              'dt_birth_events.item_id',
              'dt_birth_events.display_key',
              'dt_diagnosis.source_identifier',
              'dt_diagnosis.source_string',
              'dt_diagnosis.n_source_vocabulary_disp',
              'dt_icd_procedures.code',
              'dt_icd_procedures.description',
              'dt_icd_procedures.type',
              'dt_lab_items.item_id',
              'dt_lab_items.label',
              'dt_lab_items_category.category_id',
              'dt_lab_items_category.label',
              'dt_labitems.labitem_description',
              'dt_labitems.labitem_description_category',
              'dt_para_events.item_id',
              'dt_para_events.display_key',
              'dt_vitals.vitals_event']

